site_name: THU Xiaogroup Wiki
site_url: https://sitename.example
repo_name: xiaohaigroup/xiaohaigroup.github.io
repo_url: https://github.com/xiaohaigroup/xiaohaigroup.github.io

extra:
  social:
    - icon: material/web
      link: https://sitename.example
      name: 课题组网站
    - icon: fontawesome/brands/github
      link: https://github.com/xiaohaigroup
      name: 课题组Github
    - icon: fontawesome/solid/paper-plane
      link: haixiao@tsinghua.edu.cn
      name: 联系肖海老师
  alternate:
    - name: 中文
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en
  author_name: '{{ page.meta.authors }}'


theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/graduation-cap
    repo: fontawesome/brands/github
  # logo: images/logo.png
  # favicon: images/favicon.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  favicon: images/favicon.png

  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.tooltips
    - search.suggest
    - content.code.annotate

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/analytic.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/avatar.css
  - css/extra.css

copyright: "Copyright © 2025 Yue Yin; Hai Xiao"


nav:
  - Home: index.md
  - WIKI:
      - How to add a page: how-to-add-a-page.md
      - qyz-test: qyz-test.md
      - Admonitions: admonitions.md
      - Code-examples: code-examples.md
      - Content-tabs: content-tabs.md
      - Diagram-examples: diagram-examples.md
  - Issues:
      - Windows User Variable: issues/windows_user_variables.md